// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSYhrdldmWpkk-XUL-1d4YLn6IJhggqik',
    appId: '1:796509337071:web:c98d3381cdef2aff2d321a',
    messagingSenderId: '796509337071',
    projectId: 'vendor-app-8ebba',
    authDomain: 'vendor-app-8ebba.firebaseapp.com',
    storageBucket: 'vendor-app-8ebba.firebasestorage.app',
    measurementId: 'G-RLZ31F8FEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjgIGXwGZdf4J0_q7qpOB7A09qyGIrlUo',
    appId: '1:796509337071:android:81efeb1a5e25b2782d321a',
    messagingSenderId: '796509337071',
    projectId: 'vendor-app-8ebba',
    storageBucket: 'vendor-app-8ebba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlfiUp1_QUMpstN-XkZVs_UPkkx5V9jY',
    appId: '1:796509337071:ios:38fc7148f4d690812d321a',
    messagingSenderId: '796509337071',
    projectId: 'vendor-app-8ebba',
    storageBucket: 'vendor-app-8ebba.firebasestorage.app',
    iosBundleId: 'com.example.vendorChemTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOlfiUp1_QUMpstN-XkZVs_UPkkx5V9jY',
    appId: '1:796509337071:ios:38fc7148f4d690812d321a',
    messagingSenderId: '796509337071',
    projectId: 'vendor-app-8ebba',
    storageBucket: 'vendor-app-8ebba.firebasestorage.app',
    iosBundleId: 'com.example.vendorChemTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSYhrdldmWpkk-XUL-1d4YLn6IJhggqik',
    appId: '1:796509337071:web:937788d82800da562d321a',
    messagingSenderId: '796509337071',
    projectId: 'vendor-app-8ebba',
    authDomain: 'vendor-app-8ebba.firebaseapp.com',
    storageBucket: 'vendor-app-8ebba.firebasestorage.app',
    measurementId: 'G-BG3EBP3M5B',
  );
}
